version: '2'
services:
  app:
    container_name: koel
    build: ./img
    ports:
    - "10022:80"
    volumes:
    - /media/Music:/app/music
    environment:
    - ADMIN_EMAIL=mickael@kerjean.me
    - ADMIN_PASSWORD=test
    - ADMIN_NAME=Mickael
    - HTTPS=true
    - DB_CONNECTION=mysql
    - DB_HOST=db
    - DB_USERNAME=koel
    - DB_PASSWORD=koel
    - DB_DATABASE=koel
    - MEMORY_LIMIT=2048
    - APP_MAX_SCAN_TIME=3600
    - FFMPEG_PATH=/usr/bin/ffmpeg
    - MEDIA_PATH=/app/music
    restart: always
    
  db:
    container_name: koel_db
    image: mysql
    restart: always
    environment:
    - MYSQL_DATABASE=koel
    - MYSQL_PASSWORD=koel
    - MYSQL_ROOT_PASSWORD=koel
    - MYSQL_USER=koel
    volumes:
    - ./data/db:/var/lib/mysql

    
